'use client';

import { useState, useEffect, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import BackButton from '@/components/BackButton';
import Combobox from '@/components/Combobox';

interface Category {
  id: number;
  name: string;
}

interface ProductType {
  id: number;
  category_id: number;
  name: string;
  default_specs: string; // JSON string
}

interface ProductFormProps {
  categories: Category[];
  types: ProductType[];
  preselectedType: string;
}

interface RecentProduct {
  id: number;
  name: string;
  reference: string | null;
  selling_price: number;
  stock: number;
  type_name: string | null;
}

export default function ProductForm({ categories, types, preselectedType }: ProductFormProps) {
  const router = useRouter();

  // Preselected type parsing for matching SSR/hydration initial state
  const foundPreselectedType = useMemo(() => {
    if (!preselectedType) return null;
    return types.find(t => t.id.toString() === preselectedType);
  }, [preselectedType, types]);

  // Form fields
  const [name, setName] = useState('');
  const [reference, setReference] = useState('');
  const [selectedCatId, setSelectedCatId] = useState(foundPreselectedType ? foundPreselectedType.category_id.toString() : '');
  const [selectedTypeId, setSelectedTypeId] = useState(preselectedType || '');
  const [purchasePrice, setPurchasePrice] = useState('');
  const [sellingPrice, setSellingPrice] = useState('');
  const [stock, setStock] = useState('0');
  const [nombreColis, setNombreColis] = useState('');

  // Specs states
  const [defaultSpecsList, setDefaultSpecsList] = useState<any[]>(() => {
    if (!foundPreselectedType) return [];
    try {
      return JSON.parse(foundPreselectedType.default_specs || '[]');
    } catch (e) {
      return [];
    }
  });
  const [specValues, setSpecValues] = useState<Record<string, string>>({});
  const [customSpecs, setCustomSpecs] = useState<{ name: string; value: string }[]>([]);

  // Page modes
  const [addMultiple, setAddMultiple] = useState(false);
  const [recentProducts, setRecentProducts] = useState<RecentProduct[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Autogenerated reference state
  const [isRefManuallyEdited, setIsRefManuallyEdited] = useState(false);
  const [currentRandom, setCurrentRandom] = useState(() => Math.random().toString(36).substring(2, 6).toUpperCase());

  // Filter types based on category
  const filteredTypes = useMemo(() => {
    if (!selectedCatId) return [];
    return types.filter(t => t.category_id.toString() === selectedCatId);
  }, [types, selectedCatId]);

  // Handle Category select
  const handleCategoryChange = (catId: string) => {
    setSelectedCatId(catId);
    setSelectedTypeId('');
    setDefaultSpecsList([]);
    setSpecValues({});
  };

  // Handle Type select
  const handleTypeChange = (typeId: string) => {
    setSelectedTypeId(typeId);
    setSpecValues({});

    if (!typeId) {
      setDefaultSpecsList([]);
      return;
    }

    const t = types.find(item => item.id.toString() === typeId);
    if (t) {
      try {
        const parsed = JSON.parse(t.default_specs || '[]');
        setDefaultSpecsList(parsed);
      } catch (e) {
        setDefaultSpecsList([]);
      }
    }
  };

  // Handle default spec inputs
  const handleSpecValChange = (name: string, val: string) => {
    setSpecValues(prev => ({ ...prev, [name]: val }));
  };

  // Handle custom specs
  const handleAddCustomSpec = () => {
    setCustomSpecs(prev => [...prev, { name: '', value: '' }]);
  };

  const handleRemoveCustomSpec = (index: number) => {
    setCustomSpecs(prev => prev.filter((_, i) => i !== index));
  };

  const handleCustomSpecChange = (index: number, field: 'name' | 'value', val: string) => {
    setCustomSpecs(prev => prev.map((item, i) => i === index ? { ...item, [field]: val } : item));
  };

  // Initialize preselected type
  useEffect(() => {
    if (preselectedType) {
      const foundType = types.find(t => t.id.toString() === preselectedType);
      if (foundType) {
        setSelectedCatId(foundType.category_id.toString());
        setSelectedTypeId(foundType.id.toString());
        try {
          setDefaultSpecsList(JSON.parse(foundType.default_specs || '[]'));
        } catch (e) {}
      }
    }
  }, [preselectedType, types]);

  // Handle automatic reference generation
  useEffect(() => {
    if (isRefManuallyEdited) return;
    const trimmedName = name.trim();
    if (!trimmedName) {
      setReference('');
      return;
    }
    const words = trimmedName.split(/\s+/).filter(w => w.length > 0);
    const initials = words.map(w => w[0]).join('').substring(0, 3).toUpperCase();
    setReference(`${initials}-${currentRandom}`);
  }, [name, isRefManuallyEdited, currentRandom]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    const qty = Number(stock);
    if (isNaN(qty) || qty < 0) {
      setError('المخزون الأولي لا يمكن أن يكون سالباً');
      return;
    }

    setLoading(true);

    // Merge default and custom specifications
    const specifications: Record<string, string> = {};
    
    // Add default specs
    defaultSpecsList.forEach(spec => {
      const specName = typeof spec === 'object' ? spec.name : spec;
      specifications[specName] = specValues[specName] || '';
    });

    // Add custom specs
    customSpecs.forEach(spec => {
      if (spec.name.trim() !== '') {
        specifications[spec.name.trim()] = spec.value;
      }
    });

    try {
      const response = await fetch('/api/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type_id: selectedTypeId ? Number(selectedTypeId) : null,
          name,
          reference,
          purchase_price: purchasePrice || 0,
          selling_price: sellingPrice || 0,
          stock: stock || 0,
          nombre_colis: nombreColis === '' ? null : Number(nombreColis),
          specifications
        })
      });

      const resData = await response.json();
      if (!response.ok) {
        throw new Error(resData.error || 'حدث خطأ أثناء حفظ المنتج.');
      }

      if (addMultiple) {
        // Prepend to recent list
        const p = resData.product;
        if (p) {
          setRecentProducts(prev => [
            {
              id: p.id,
              name: p.name,
              reference: p.reference,
              selling_price: p.selling_price,
              stock: p.stock,
              type_name: p.type_name
            },
            ...prev
          ]);
        }

        // Reset fields
        setName('');
        setReference('');
        setPurchasePrice('');
        setSellingPrice('');
        setStock('0');
        setNombreColis('');
        setSpecValues({});
        setCustomSpecs([]);
        setIsRefManuallyEdited(false);
        setCurrentRandom(Math.random().toString(36).substring(2, 6).toUpperCase());
        
        // Focus name input
        document.getElementById('nameInput')?.focus();
      } else {
        router.back();
        router.refresh();
      }
    } catch (err: any) {
      setError(err.message || 'حدث خطأ ما');
    } finally {
      setLoading(false);
    }
  };

  const openTypeManager = () => {
    if (typeof window !== 'undefined' && (window as any).openTypeManager) {
      (window as any).openTypeManager();
    }
  };

  return (
    <>
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <h2 className="h2 mb-0">إضافة منتج</h2>
        </div>
        <div className="flex items-center gap-3">
          <label className="toggle-switch">
            <input 
              type="checkbox" 
              id="addMultipleToggle" 
              checked={addMultiple}
              onChange={(e) => setAddMultiple(e.target.checked)}
            />
            <span className="toggle-slider"></span>
          </label>
          <label htmlFor="addMultipleToggle" className="text-sm font-semibold cursor-pointer select-none">تفعيل إضافة منتجات متعددة متتالية</label>
          <BackButton fallbackHref="/products" />
        </div>
      </div>

      <div className="card max-w-2xl mb-6">
        {error && <div className="badge badge-danger p-4 w-full mb-4">{error}</div>}
        
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold mb-1">اسم المنتج *</label>
              <input 
                type="text" 
                id="nameInput"
                required 
                className="input" 
                placeholder="مثال: دفتر 96 صفحة" 
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-semibold mb-1">المرجع *</label>
              <input 
                type="text" 
                required 
                className="input" 
                placeholder="مثال: CAH-96" 
                value={reference}
                onChange={(e) => {
                  setReference(e.target.value);
                  setIsRefManuallyEdited(e.target.value.trim() !== '');
                }}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold mb-1">الفئة *</label>
              <select 
                required 
                className="input"
                value={selectedCatId}
                onChange={(e) => handleCategoryChange(e.target.value)}
              >
                <option value="">اختر الفئة...</option>
                {categories.map(cat => (
                  <option key={cat.id} value={cat.id}>{cat.name}</option>
                ))}
              </select>
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-semibold">نوع المنتج *</label>
                <button 
                  type="button" 
                  className="text-brand text-xs font-semibold hover:underline" 
                  onClick={openTypeManager}
                >
                  + إدارة الفئات والأنواع
                </button>
              </div>
              <select 
                required 
                className="input" 
                disabled={!selectedCatId}
                value={selectedTypeId}
                onChange={(e) => handleTypeChange(e.target.value)}
              >
                <option value="">{selectedCatId ? 'اختر نوع المنتج...' : 'اختر الفئة أولاً...'}</option>
                {filteredTypes.map(t => (
                  <option key={t.id} value={t.id}>{t.name}</option>
                ))}
              </select>
            </div>
          </div>
          
          <div id="specsSection" className="bg-gray-50 p-4 rounded-lg border border-border">
            <h4 className="font-semibold text-sm mb-3">المواصفات (Specifications)</h4>
            
            <div id="dynamicSpecsContainer" className="flex flex-col gap-3 mb-3">
              {defaultSpecsList.length === 0 && selectedTypeId && (
                <span className="text-xs text-light">لا توجد خصائص افتراضية لهذا النوع.</span>
              )}
              {defaultSpecsList.map((spec, index) => {
                const isObj = typeof spec === 'object';
                const specName = isObj ? spec.name : spec;
                const options = isObj ? (spec.options || []) : [];
                return (
                  <div key={index} className="flex items-center gap-2">
                    <label className="w-1/3 text-sm text-text">{specName}</label>
                    {options.length > 0 ? (
                      <Combobox
                        placeholder={`قيمة ${specName}...`}
                        value={specValues[specName] || ''}
                        options={options}
                        onChange={(newVal) => handleSpecValChange(specName, newVal)}
                      />
                    ) : (
                      <input 
                        type="text" 
                        className="input flex-1" 
                        placeholder={`قيمة ${specName}...`} 
                        value={specValues[specName] || ''}
                        onChange={(e) => handleSpecValChange(specName, e.target.value)}
                      />
                    )}
                  </div>
                );
              })}
            </div>

            <div id="customSpecsContainer" className="flex flex-col gap-3 mb-3 border-t border-border pt-3 mt-3">
              {customSpecs.map((spec, index) => (
                <div key={index} className="flex items-center gap-2">
                  <input 
                    type="text" 
                    className="input w-1/3" 
                    placeholder="اسم الخاصية..." 
                    value={spec.name}
                    onChange={(e) => handleCustomSpecChange(index, 'name', e.target.value)}
                    required 
                  />
                  <input 
                    type="text" 
                    className="input flex-1" 
                    placeholder="القيمة..." 
                    value={spec.value}
                    onChange={(e) => handleCustomSpecChange(index, 'value', e.target.value)}
                    required 
                  />
                  <button 
                    type="button" 
                    className="btn btn-outline text-danger border-danger px-2"
                    onClick={() => handleRemoveCustomSpec(index)}
                  >
                    &times;
                  </button>
                </div>
              ))}
            </div>

            <button type="button" className="btn btn-outline text-xs mt-2" onClick={handleAddCustomSpec}>+ إضافة خاصية</button>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div>
              <label className="block text-sm font-semibold mb-1">سعر الشراء</label>
              <input 
                type="number" 
                step="0.01" 
                className="input" 
                placeholder="0.00" 
                value={purchasePrice}
                onChange={(e) => setPurchasePrice(e.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-semibold mb-1">سعر البيع *</label>
              <input 
                type="number" 
                step="0.01" 
                required 
                className="input" 
                placeholder="0.00" 
                value={sellingPrice}
                onChange={(e) => setSellingPrice(e.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-semibold mb-1">المخزون الأولي</label>
              <input 
                type="number" 
                min="0"
                className="input" 
                placeholder="0" 
                value={stock}
                onChange={(e) => setStock(e.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-semibold mb-1">عدد الطرود (اختياري)</label>
              <input 
                type="number" 
                min="0"
                className="input" 
                placeholder="مثال: 5" 
                value={nombreColis}
                onChange={(e) => setNombreColis(e.target.value)}
              />
            </div>
          </div>

          <div className="mt-4 flex justify-end border-t border-border pt-4">
            <button type="submit" className="btn btn-primary" disabled={loading}>
              {loading ? 'جاري الحفظ...' : addMultiple ? 'حفظ وإضافة منتج آخر' : 'حفظ المنتج'}
            </button>
          </div>
        </form>
      </div>

      {recentProducts.length > 0 && (
        <div className="card">
          <h3 className="h3 mb-4">المنتجات المضافة حديثاً</h3>
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  <th>المرجع</th>
                  <th>المنتج</th>
                  <th>النوع</th>
                  <th>سعر البيع</th>
                  <th>المخزون</th>
                </tr>
              </thead>
              <tbody>
                {recentProducts.map(p => (
                  <tr key={p.id}>
                    <td><span className="badge badge-info">{p.reference || '-'}</span></td>
                    <td className="font-bold">{p.name}</td>
                    <td>{p.type_name || '-'}</td>
                    <td className="font-bold text-brand">{p.selling_price} درهم</td>
                    <td>{p.stock}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </>
  );
}
